name: Training session
description: Create a training session
title: "training"
labels: [training]
body:
  - type: markdown
    attributes:
      value: |
        Create a new training session
  - type: input
    id: trainer
    attributes:
      label: Session trainer
      description: Trainer for this session
      placeholder: ex. sylvain.martinez@cellenza.com
    validations:
      required: true
  - type: textarea
    id: trainees
    attributes:
      label: List of trainees
      description: List of trainees
      placeholder: List of trainees
      value: "List of trainees"
    validations:
      required: true
  - type: dropdown
    id: sessionType
    attributes:
      label: Session Type
      description: What kind of formation?
      options:
        - Terraform introduction
        - Terraform intermediate
        - Terraform Azure DevOps
    validations:
      required: true

