name: PR

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    paths-ignore:
      - trainings/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Tests
        shell: pwsh
        run: ./tests/Invoke-Tests.ps1 -testTag @("UnitTests")