name: PR

on:
  pull_request:
    paths-ignore:
      - trainings/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Unit Tests
        shell: pwsh
        run: ./tests/Invoke-Tests.ps1 -testTag @("UnitTests")