name: training

on:
  issues:
    types: [opened, edited]

jobs:
  initialize_training:
    runs-on: ubuntu-latest
    steps:
      # - name: View issue information
      #   run: |
      #     echo "Issue title: ${{ github.event.issue.title }}"
      #     echo "Issue body: ${{ github.event.issue.body }}"

# You also can print the whole github context to the logs to view more details.
      # - name: View the github context
      #   run: echo "$GITHUB_CONTEXT"
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: main

      - name: Get Training summary
        id: get_training_summary
        shell: pwsh
        run: ./src/GetSummary.ps1 -issueMarkdownContent '${{ github.event.issue.body }}' -issueName ${{ github.event.issue.title }} -issueUrl ${{ github.event.issue.html_url }}

      - name: Create training branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        uses: peterjgrainger/action-create-branch@v2.0.1
        with:
          branch: 'trainings/${{ github.event.issue.title }}'

      - name: Clone training branch
        uses: actions/checkout@v2
        with:
          ref: 'trainings/${{ github.event.issue.title }}'
          path: 'trainingBranch'

      - name: Add new training session file
        shell: pwsh
        run: |
          Copy-Item -Path ${{ github.event.issue.title }}.json -Destination trainingBranch/trainings

      - name: Commit new training
        uses: EndBug/add-and-commit@v7
        with:
          cwd: 'trainingBranch'
          add: 'trainings/${{ github.event.issue.title }}.json'
          message: 'Add new training ${{ github.event.issue.title }}'
          branch: 'trainings/${{ github.event.issue.title }}'

      - name: Create Pull Request
        id: create_pull_request
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          source_branch: 'trainings/${{ github.event.issue.title }}'
          destination_branch: 'main'
          pr_title: 'Add new training ${{ github.event.issue.title }}'
          pr_body: "This Pull Request has been automatically created for your next training. Related to Issue ${{ github.event.issue.html_url }}"
          pr_assigne: '${{ steps.get_training_summary.outputs.trainerEmail }}'

      - name: Comment issue with summary
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for creating this training, you're really my favorite user you know :heart:
            Trainer has been assigned a Pull Request and should do its work now.
            The PR is this one : ${{ steps.create_pull_request.outputs.pr_url }}

            Really, you're the best, a real asset for Cellenza